#!/usr/bin/env bash

build() {
    if ! pacman -Qi clevis >/dev/null 2>&1; then
        error "Package clevis not installed"
        return 1
    fi

    # dependencies
    add_binary /usr/lib/initcpio/busybox /usr/bin/busybox
    local applet
    for applet in $(/usr/lib/initcpio/busybox --list); do
        add_symlink "/usr/bin/$applet" busybox
    done

    add_binary bash
    add_binary jose
    add_binary curl
    add_binary cryptsetup
    add_binary grep
    add_binary tr

    # clevis with tang server
    add_binary clevis
    add_binary clevis-luks-common-functions
    add_binary clevis-luks-unlock
    add_binary clevis-decrypt
    add_binary clevis-decrypt-tang

    # clevis with tpm2
    if ! pacman -Qi tpm2-tools >/dev/null 2>&1; then
        warning "Package tpm2-tools not installed. Unlocking via tpm2 will not work"
    else
        add_binary tpm2_createprimary
        add_binary tpm2_load
        add_binary tpm2_unseal
        add_binary tpm2_flushcontext
        add_binary clevis-decrypt-tpm2

        local libtss2
        for libtss2 in /usr/lib/libtss2-tcti-device.so*; do
            add_binary "${libtss2}"
        done
    fi

    add_file /usr/lib/systemd/systemd-reply-password

    add_systemd_unit clevis-luks-askpass.service
    add_systemd_unit clevis-luks-askpass.path
    add_symlink /etc/systemd/system/sysinit.target.wants/clevis-luks-askpass.path \
                /usr/lib/systemd/system/clevis-luks-askpass.path
}

help() {
    cat <<__EOF_HELP__
This hook allows for unlocking an encrypted root volume with clevis. tang and
tpm2 bound volumes are supported.

The hook must be placed after sd-tinyssh and sd-dropbear, because of its
dependency on grep -B, which is not supported by busybox used in those hooks.
__EOF_HELP__
}

