#!/bin/bash

build() {
    add_systemd_unit systemd-networkd.service

    # enable systemd-networkd.service
    add_symlink /etc/systemd/system/sysinit.target.wants/systemd-networkd.service \
                /usr/lib/systemd/system/systemd-networkd.service

    SD_NETWORK_CONFIG="${SD_NETWORK_CONFIG:-/etc/systemd/network}"
    if [[ ! -d "$SD_NETWORK_CONFIG" ]]; then
        error "${SD_NETWORK_CONFIG} does not exist"
        return 1
    fi

    add_dir /etc/systemd/network
    (cd "$SD_NETWORK_CONFIG"; cp -ra -t "$BUILDROOT/etc/systemd/network" .)

    add_checked_modules /drivers/net

    # systemd-networkd.service requires user systemd-network
    grep '^systemd-network:' /etc/passwd >>"$BUILDROOT/etc/passwd"
    grep '^systemd-network:' /etc/shadow >>"$BUILDROOT/etc/shadow"
    grep '^systemd-network:' /etc/group >>"$BUILDROOT/etc/group"
}

help() {
    cat <<__EOF_HELP__
This hook allows for initial network setup with systemd initramfs.

It copies all files, binaries and drivers required by systemd-networkd to the
initramfs and enables systemd-networkd.service. Network configuration is copied
from /etc/systemd/network or from \$SD_NETWORK_CONFIG if this variable
specifies an existing directory. SD_NETWORK_CONFIG must be set in
/etc/mkinitcpio.conf.

See https://github.com/wolegis/mkinitcpio-systemd-extras/wiki/Networking for
details, especially about how to deal with network interface names differing
between initramfs phase and the final operating environment.
__EOF_HELP__
}
